### PR TITLE
Tara's About Me

### PR DESCRIPTION
**Pull request by TaraMathur**
Uploading Tara's About Me files to replace the quick About Me I uploaded last week.

### CODE REVIEW

**Comment by andrewlw89** [comment]
Hey Tara, looks like you are behind master by ~47 commits and have an older index.html in your pull request. You could try updating master on local then rebase into your branch from that. You'll get a merge conflict but you could fix that then push again to get all up to date.

**Comment by TaraMathur** [comment]
Thanks Andrew,

I used the editor in GitKraken to resolve the conflict so I think I should
be all set.  (But will you double-check?:)

Tara

**Review by andrewlw89 — APPROVED** [review]
Changes look good to me. I'd say ship it unless someone else sees something I'm missing.

**Comment by ghost** [comment]
LGTM

**Comment by TaraMathur** [comment]
Thanks - I'm still many commits behind master so I still need to take care of that before I merge.

**Review by bauer-hillary-c — APPROVED** [review]

**Pull request merged**
